services:
  wireguard:
    container_name: wireguard
    image: jordanpotter/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - /etc/wireguard/octobot.conf:/etc/wireguard/wg0.conf
    restart: unless-stopped

  octobot:
    container_name: octobot
    build:
      context: .
      args:
        - PUBLISH_OPTIONS
    environment:
      - BOT_TOKEN
    network_mode: service:wireguard
    depends_on:
      - wireguard
    volumes:
      - guild-data:/Octobot/GuildData
      - logs:/Octobot/Logs
    restart: unless-stopped

volumes:
  guild-data:
  logs:
