name: Bug Report
description: Create a report to help us improve
labels: [ "type: bug" ]
body:
    - type: markdown
      attributes:
          value: |
              We welcome bug reports! Please see our [contribution guidelines](docs/CONTRIBUTING.md#reporting-bugs) for more information on writing a good bug report. This template will help us gather the information we need to start the triage process.
    - type: textarea
      id: background
      attributes:
          label: Description
          description: Please share a clear and concise description of the problem.
          placeholder: Description
      validations:
          required: true
    - type: textarea
      id: expected-vs-actual-behavior
      attributes:
        label: Expected vs. Actual Behavior
        description: |
          Provide a description of the expected behavior compared to the actual behavior.
        placeholder: Expected vs. Actual Behavior
      validations:
        required: true
    - type: textarea
      id: repro-steps
      attributes:
          label: Reproduction Steps
          description: |
              Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible command/action sequence. If possible include text as text rather than screenshots (so it shows up in searches).
          placeholder: Minimal Reproduction
      validations:
          required: true
    - type: textarea
      id: other-info
      attributes:
          label: Other Information
          description: |
              If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
          placeholder: Other Information
      validations:
          required: false
