name: Feature Request
description: Create a request for a feature you would like
labels: [ "type: enhancement" ]
body:
    - type: textarea
      id: background
      attributes:
          label: Description
          description: Please share a clear and concise description of the feature you want.
          placeholder: Description
      validations:
          required: true
    - type: textarea
      id: proposed-solution
      attributes:
          label: Proposed Solution
          description: Please describe the solution you would like.
          placeholder: Proposed Solution
      validations:
          required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Considered Alternatives
          description: |
              Please provide a description of any alternative solutions or features you've considered.
          placeholder: Considered Alternatives
      validations:
          required: false
    - type: textarea
      id: other-info
      attributes:
          label: Other Information
          description: |
              Please add any other context or screenshots about the feature request here.
          placeholder: Other Information
      validations:
          required: false
